---
- name: Deploy base apps
  hosts: all
  become: true
  roles:
  - epel
  - common

- name: Deploy nodes
  hosts: nodes
  become: true
  roles:
  - pacemaker

- name: Deploy fronts
  hosts: fronts
  become: true
  roles:
  - nginx

